// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StyleGenie.Infrastructure.Data.Models;

#nullable disable

namespace StyleGenie.Infrastructure.Migrations
{
    [DbContext(typeof(TryOnDbContext))]
    partial class TryOnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OutfitItem", b =>
                {
                    b.Property<long>("OutfitId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.HasKey("OutfitId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("OutfitItems", (string)null);
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.AIStylingHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("ClickedAffiliate")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("FilterCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OutfitId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SavedToCloset")
                        .HasColumnType("bit");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__AIStylin__3214EC07A4CDDEF3");

                    b.HasIndex("OutfitId");

                    b.HasIndex("UserId");

                    b.ToTable("AIStylingHistory");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.AdsClickLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BannerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ClickedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DestinationUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__AdsClick__3214EC075D10E22E");

                    b.HasIndex("BannerId");

                    b.HasIndex("UserId");

                    b.ToTable("AdsClickLog");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.AffiliateLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ClickCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CommissionRate")
                        .HasColumnType("decimal(6, 4)");

                    b.Property<int>("ConversionCount")
                        .HasColumnType("int");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Affiliat__3214EC07E6E003D0");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("AffiliateLinks");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.AnalyticsLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Analytic__3214EC077C51604A");

                    b.HasIndex("UserId");

                    b.ToTable("AnalyticsLogs");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ApiCredential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SecretCipher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id")
                        .HasName("PK__ApiCrede__3214EC07E7083C79");

                    b.HasIndex(new[] { "TenantId", "Provider", "KeyName" }, "UX_ApiCredentials")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("ApiCredentials");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ApiKeys", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.AttributeType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id")
                        .HasName("PK__Attribut__3214EC07AEA67981");

                    b.ToTable("AttributeTypes");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.AttributeValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AttributeTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("HexColor")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("char(7)")
                        .IsFixedLength();

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id")
                        .HasName("PK__Attribut__3214EC07EFE08416");

                    b.HasIndex("AttributeTypeId");

                    b.ToTable("AttributeValues");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Banner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("DestinationUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("DisplayPosition")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("ImageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Banners__3214EC07F43F36C2");

                    b.HasIndex("ImageId");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07121B8EFA");

                    b.HasIndex("ParentId");

                    b.HasIndex("TenantId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Closet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Closets__3214EC0774301F9A");

                    b.HasIndex("UserId");

                    b.ToTable("Closets");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ClosetCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClosetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id")
                        .HasName("PK__ClosetCa__3214EC0758A2952E");

                    b.HasIndex("ClosetId");

                    b.ToTable("ClosetCategories");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ClosetItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClosetId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK__ClosetIt__3214EC076E5D4416");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClosetId");

                    b.HasIndex("ItemId");

                    b.ToTable("ClosetItems");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ClosetOutfitHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClosetId")
                        .HasColumnType("bigint");

                    b.Property<long>("OutfitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("SavedImages")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__ClosetOu__3214EC079EF6C131");

                    b.HasIndex("ClosetId");

                    b.HasIndex("OutfitId");

                    b.ToTable("ClosetOutfitHistory");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.CreditWallet", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("TenantId")
                        .HasName("PK__CreditWa__2E9B47E1CC818A41");

                    b.ToTable("CreditWallets");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("FeedbackType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Feedback__3214EC07760EC4BD");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Image", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<byte[]>("Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Sha256Hex")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<byte>("StorageType")
                        .HasColumnType("tinyint");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id")
                        .HasName("PK__Images__3214EC076E7BD6E2");

                    b.HasIndex(new[] { "TenantId", "Kind" }, "IX_Images_TenantId_Kind");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AffiliateUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("AttributesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVipOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("PrimaryImageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Size")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Items__3214EC07E92F6770");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PrimaryImageId");

                    b.HasIndex("TenantId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ItemAttribute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AttributeValueId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__ItemAttr__3214EC0744632D9A");

                    b.HasIndex("AttributeValueId");

                    b.HasIndex(new[] { "ItemId", "AttributeValueId" }, "UX_ItemAttributes")
                        .IsUnique();

                    b.ToTable("ItemAttributes");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ItemCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__ItemCate__3214EC07EEAB2D81");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "ItemId", "CategoryId" }, "UX_ItemCategories")
                        .IsUnique();

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Layout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsVipOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id")
                        .HasName("PK__Layouts__3214EC07B09C90F1");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Mannequin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BodyType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Gender")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVipOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SkinTone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id")
                        .HasName("PK__Mannequi__3214EC07570CBEAC");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Mannequins");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Outfit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<long?>("LayoutId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MannequinId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResultImageId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Outfits__3214EC07EE48B688");

                    b.HasIndex("LayoutId");

                    b.HasIndex("MannequinId");

                    b.HasIndex("ResultImageId");

                    b.HasIndex("UserId");

                    b.ToTable("Outfits");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderCode")
                        .HasColumnType("int");

                    b.Property<string>("PaymentLinkId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PENDING");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK__Permissi__3214EC07FBC55984");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ProductFilterLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("FilterCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResultCount")
                        .HasColumnType("int");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__ProductF__3214EC0722ECFFD4");

                    b.HasIndex("UserId");

                    b.ToTable("ProductFilterLogs");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.PromotionPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<int?>("ExtraDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Promotio__3214EC0726C1712B");

                    b.ToTable("PromotionPlans");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Report", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("HandledBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("OPEN");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Reports__3214EC0783CF5574");

                    b.HasIndex("HandledBy");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07A0900E75");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__RolePerm__3214EC077ABA786C");

                    b.HasIndex("PermissionId");

                    b.HasIndex(new[] { "RoleId", "PermissionId" }, "UX_RolePermissions")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.SkinToneAnalysisLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AnalysisResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DetectedSkinTone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__SkinTone__3214EC07D321E484");

                    b.HasIndex("UserId");

                    b.ToTable("SkinToneAnalysisLog");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.SkinToneColorRecommendation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("char(7)")
                        .IsFixedLength();

                    b.Property<string>("SkinTone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id")
                        .HasName("PK__SkinTone__3214EC07869C7FE8");

                    b.ToTable("SkinToneColorRecommendations");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.SubscriptionPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("HasAds")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWatermark")
                        .HasColumnType("bit");

                    b.Property<int?>("MannequinLimit")
                        .HasColumnType("int");

                    b.Property<int?>("MaxItemsPerDay")
                        .HasColumnType("int");

                    b.Property<int?>("MaxLayoutsPerDay")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Subscrip__3214EC0722E6570D");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.TemporaryRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Temporar__3214EC0789556771");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("TemporaryRoles");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("Id")
                        .HasName("PK__Tenants__3214EC07E4362A53");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC077BCA6749");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.TryOnJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClothImageId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClothType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Error")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("HdMode")
                        .HasColumnType("bit");

                    b.Property<long?>("LowerClothImageId")
                        .HasColumnType("bigint");

                    b.Property<long>("ModelImageId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ProviderTaskId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("ResultImageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__TryOnJob__3214EC079CB4B82D");

                    b.HasIndex("ClothImageId");

                    b.HasIndex("LowerClothImageId");

                    b.HasIndex("ModelImageId");

                    b.HasIndex("ResultImageId");

                    b.HasIndex(new[] { "TenantId", "CreatedAt" }, "IX_TryOnJobs_TenantId_CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("TryOnJobs");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.UsageLedger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<long?>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__UsageLed__3214EC07D4736902");

                    b.HasIndex("JobId");

                    b.HasIndex(new[] { "TenantId", "CreatedAt" }, "IX_UsageLedger_TenantId_CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("UsageLedger");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AvatarImageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("SkinTone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("SubscriptionPlanId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC070E310D8A");

                    b.HasIndex("AvatarImageId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "Email" }, "UX_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.UserPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__UserPerm__3214EC07E14F76DE");

                    b.HasIndex("PermissionId");

                    b.HasIndex(new[] { "UserId", "PermissionId" }, "UX_UserPermissions")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.UserPromotion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("PromotionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubscriptionPlanId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__UserProm__3214EC07B2402347");

                    b.HasIndex("PromotionId");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPromotions");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.VipPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__VipPayme__3214EC0795C20CCC");

                    b.HasIndex("PlanId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("VipPayments");
                });

            modelBuilder.Entity("OutfitItem", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__OutfitIte__ItemI__22751F6C");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Outfit", null)
                        .WithMany()
                        .HasForeignKey("OutfitId")
                        .IsRequired()
                        .HasConstraintName("FK__OutfitIte__Outfi__2180FB33");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.AIStylingHistory", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Outfit", "Outfit")
                        .WithMany("AIStylingHistories")
                        .HasForeignKey("OutfitId")
                        .HasConstraintName("FK__AIStyling__Outfi__681373AD");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("AIStylingHistories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__AIStyling__UserI__671F4F74");

                    b.Navigation("Outfit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.AdsClickLog", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Banner", "Banner")
                        .WithMany("AdsClickLogs")
                        .HasForeignKey("BannerId")
                        .IsRequired()
                        .HasConstraintName("FK__AdsClickL__Banne__44CA3770");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("AdsClickLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__AdsClickL__UserI__43D61337");

                    b.Navigation("Banner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.AffiliateLink", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Item", "Item")
                        .WithMany("AffiliateLinks")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Affiliate__ItemI__3B40CD36");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("AffiliateLinks")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Affiliate__UserI__3A4CA8FD");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.AnalyticsLog", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("AnalyticsLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Analytics__UserI__5224328E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ApiCredential", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Tenant", "Tenant")
                        .WithMany("ApiCredentials")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK__ApiCreden__Tenan__628FA481");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.AttributeValue", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.AttributeType", "AttributeType")
                        .WithMany("AttributeValues")
                        .HasForeignKey("AttributeTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Attribute__Attri__08B54D69");

                    b.Navigation("AttributeType");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Banner", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Image", "Image")
                        .WithMany("Banners")
                        .HasForeignKey("ImageId")
                        .HasConstraintName("FK__Banners__ImageId__40058253");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Category", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__Categorie__Paren__75A278F5");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Tenant", "Tenant")
                        .WithMany("Categories")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK__Categorie__Tenan__74AE54BC");

                    b.Navigation("Parent");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Closet", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("Closets")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Closets__UserId__25518C17");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ClosetCategory", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Closet", "Closet")
                        .WithMany("ClosetCategories")
                        .HasForeignKey("ClosetId")
                        .IsRequired()
                        .HasConstraintName("FK__ClosetCat__Close__2A164134");

                    b.Navigation("Closet");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ClosetItem", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.ClosetCategory", "Category")
                        .WithMany("ClosetItems")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__ClosetIte__Categ__30C33EC3");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Closet", "Closet")
                        .WithMany("ClosetItems")
                        .HasForeignKey("ClosetId")
                        .IsRequired()
                        .HasConstraintName("FK__ClosetIte__Close__2EDAF651");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Item", "Item")
                        .WithMany("ClosetItems")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__ClosetIte__ItemI__2FCF1A8A");

                    b.Navigation("Category");

                    b.Navigation("Closet");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ClosetOutfitHistory", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Closet", "Closet")
                        .WithMany("ClosetOutfitHistories")
                        .HasForeignKey("ClosetId")
                        .IsRequired()
                        .HasConstraintName("FK__ClosetOut__Close__3493CFA7");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Outfit", "Outfit")
                        .WithMany("ClosetOutfitHistories")
                        .HasForeignKey("OutfitId")
                        .IsRequired()
                        .HasConstraintName("FK__ClosetOut__Outfi__3587F3E0");

                    b.Navigation("Closet");

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.CreditWallet", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Tenant", "Tenant")
                        .WithOne("CreditWallet")
                        .HasForeignKey("StyleGenie.Infrastructure.Data.Models.CreditWallet", "TenantId")
                        .IsRequired()
                        .HasConstraintName("FK__CreditWal__Tenan__59063A47");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Feedback", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Feedback__UserId__489AC854");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Image", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Tenant", "Tenant")
                        .WithMany("Images")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK__Images__TenantId__66603565");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Item", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "CreatedByNavigation")
                        .WithMany("Items")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Items__CreatedBy__7D439ABD");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Image", "PrimaryImage")
                        .WithMany("Items")
                        .HasForeignKey("PrimaryImageId")
                        .HasConstraintName("FK__Items__PrimaryIm__7A672E12");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Tenant", "Tenant")
                        .WithMany("Items")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK__Items__TenantId__797309D9");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("PrimaryImage");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ItemAttribute", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.AttributeValue", "AttributeValue")
                        .WithMany("ItemAttributes")
                        .HasForeignKey("AttributeValueId")
                        .IsRequired()
                        .HasConstraintName("FK__ItemAttri__Attri__0D7A0286");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Item", "Item")
                        .WithMany("ItemAttributes")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__ItemAttri__ItemI__0C85DE4D");

                    b.Navigation("AttributeValue");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ItemCategory", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("ItemCategories")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__ItemCateg__Categ__03F0984C");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Item", "Item")
                        .WithMany("ItemCategories")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__ItemCateg__ItemI__02FC7413");

                    b.Navigation("Category");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Layout", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "CreatedByNavigation")
                        .WithMany("Layouts")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Layouts__Created__17036CC0");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Mannequin", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "CreatedByNavigation")
                        .WithMany("Mannequins")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Mannequin__Creat__123EB7A3");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Outfit", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Layout", "Layout")
                        .WithMany("Outfits")
                        .HasForeignKey("LayoutId")
                        .HasConstraintName("FK__Outfits__LayoutI__1BC821DD");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Mannequin", "Mannequin")
                        .WithMany("Outfits")
                        .HasForeignKey("MannequinId")
                        .HasConstraintName("FK__Outfits__Mannequ__1AD3FDA4");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Image", "ResultImage")
                        .WithMany("Outfits")
                        .HasForeignKey("ResultImageId")
                        .HasConstraintName("FK__Outfits__ResultI__1CBC4616");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("Outfits")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Outfits__UserId__19DFD96B");

                    b.Navigation("Layout");

                    b.Navigation("Mannequin");

                    b.Navigation("ResultImage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Payment", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ProductFilterLog", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("ProductFilterLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__ProductFi__UserI__6EC0713C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Report", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "HandledByNavigation")
                        .WithMany("ReportHandledByNavigations")
                        .HasForeignKey("HandledBy")
                        .HasConstraintName("FK__Reports__Handled__4E53A1AA");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("ReportUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reports__UserId__4C6B5938");

                    b.Navigation("HandledByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.RolePermission", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK__RolePermi__Permi__47DBAE45");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__RolePermi__RoleI__46E78A0C");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.SkinToneAnalysisLog", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("SkinToneAnalysisLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__SkinToneA__UserI__756D6ECB");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.TemporaryRole", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Role", "Role")
                        .WithMany("TemporaryRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Temporary__RoleI__5070F446");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("TemporaryRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Temporary__UserI__4F7CD00D");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Transaction", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__UserI__55F4C372");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.TryOnJob", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Image", "ClothImage")
                        .WithMany("TryOnJobClothImages")
                        .HasForeignKey("ClothImageId")
                        .HasConstraintName("FK__TryOnJobs__Cloth__6D0D32F4");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Image", "LowerClothImage")
                        .WithMany("TryOnJobLowerClothImages")
                        .HasForeignKey("LowerClothImageId")
                        .HasConstraintName("FK__TryOnJobs__Lower__6E01572D");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Image", "ModelImage")
                        .WithMany("TryOnJobModelImages")
                        .HasForeignKey("ModelImageId")
                        .IsRequired()
                        .HasConstraintName("FK__TryOnJobs__Model__6C190EBB");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Image", "ResultImage")
                        .WithMany("TryOnJobResultImages")
                        .HasForeignKey("ResultImageId")
                        .HasConstraintName("FK__TryOnJobs__Resul__6EF57B66");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Tenant", "Tenant")
                        .WithMany("TryOnJobs")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK__TryOnJobs__Tenan__6A30C649");

                    b.Navigation("ClothImage");

                    b.Navigation("LowerClothImage");

                    b.Navigation("ModelImage");

                    b.Navigation("ResultImage");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.UsageLedger", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.TryOnJob", "Job")
                        .WithMany("UsageLedgers")
                        .HasForeignKey("JobId")
                        .HasConstraintName("FK_UsageLedger_TryOnJobs");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Tenant", "Tenant")
                        .WithMany("UsageLedgers")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK__UsageLedg__Tenan__5DCAEF64");

                    b.Navigation("Job");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.User", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Image", "AvatarImage")
                        .WithMany("Users")
                        .HasForeignKey("AvatarImageId")
                        .HasConstraintName("FK_Users_AvatarImage");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Users_Roles");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionPlanId")
                        .HasConstraintName("FK_Users_SubscriptionPlans");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__TenantId__403A8C7D");

                    b.Navigation("AvatarImage");

                    b.Navigation("Role");

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.UserPermission", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK__UserPermi__Permi__4CA06362");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserPermi__UserI__4BAC3F29");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.UserPromotion", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.PromotionPlan", "Promotion")
                        .WithMany("UserPromotions")
                        .HasForeignKey("PromotionId")
                        .IsRequired()
                        .HasConstraintName("FK__UserPromo__Promo__625A9A57");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("UserPromotions")
                        .HasForeignKey("SubscriptionPlanId")
                        .HasConstraintName("FK__UserPromo__Subsc__634EBE90");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("UserPromotions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserPromo__UserI__6166761E");

                    b.Navigation("Promotion");

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.VipPayment", b =>
                {
                    b.HasOne("StyleGenie.Infrastructure.Data.Models.SubscriptionPlan", "Plan")
                        .WithMany("VipPayments")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK__VipPaymen__PlanI__5AB9788F");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.Transaction", "Transaction")
                        .WithMany("VipPayments")
                        .HasForeignKey("TransactionId")
                        .HasConstraintName("FK__VipPaymen__Trans__5BAD9CC8");

                    b.HasOne("StyleGenie.Infrastructure.Data.Models.User", "User")
                        .WithMany("VipPayments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__VipPaymen__UserI__59C55456");

                    b.Navigation("Plan");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.AttributeType", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.AttributeValue", b =>
                {
                    b.Navigation("ItemAttributes");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Banner", b =>
                {
                    b.Navigation("AdsClickLogs");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("ItemCategories");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Closet", b =>
                {
                    b.Navigation("ClosetCategories");

                    b.Navigation("ClosetItems");

                    b.Navigation("ClosetOutfitHistories");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.ClosetCategory", b =>
                {
                    b.Navigation("ClosetItems");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Image", b =>
                {
                    b.Navigation("Banners");

                    b.Navigation("Items");

                    b.Navigation("Outfits");

                    b.Navigation("TryOnJobClothImages");

                    b.Navigation("TryOnJobLowerClothImages");

                    b.Navigation("TryOnJobModelImages");

                    b.Navigation("TryOnJobResultImages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Item", b =>
                {
                    b.Navigation("AffiliateLinks");

                    b.Navigation("ClosetItems");

                    b.Navigation("ItemAttributes");

                    b.Navigation("ItemCategories");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Layout", b =>
                {
                    b.Navigation("Outfits");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Mannequin", b =>
                {
                    b.Navigation("Outfits");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Outfit", b =>
                {
                    b.Navigation("AIStylingHistories");

                    b.Navigation("ClosetOutfitHistories");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.PromotionPlan", b =>
                {
                    b.Navigation("UserPromotions");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("TemporaryRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("UserPromotions");

                    b.Navigation("Users");

                    b.Navigation("VipPayments");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Tenant", b =>
                {
                    b.Navigation("ApiCredentials");

                    b.Navigation("Categories");

                    b.Navigation("CreditWallet");

                    b.Navigation("Images");

                    b.Navigation("Items");

                    b.Navigation("TryOnJobs");

                    b.Navigation("UsageLedgers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.Transaction", b =>
                {
                    b.Navigation("VipPayments");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.TryOnJob", b =>
                {
                    b.Navigation("UsageLedgers");
                });

            modelBuilder.Entity("StyleGenie.Infrastructure.Data.Models.User", b =>
                {
                    b.Navigation("AIStylingHistories");

                    b.Navigation("AdsClickLogs");

                    b.Navigation("AffiliateLinks");

                    b.Navigation("AnalyticsLogs");

                    b.Navigation("Closets");

                    b.Navigation("Feedbacks");

                    b.Navigation("Items");

                    b.Navigation("Layouts");

                    b.Navigation("Mannequins");

                    b.Navigation("Outfits");

                    b.Navigation("Payments");

                    b.Navigation("ProductFilterLogs");

                    b.Navigation("ReportHandledByNavigations");

                    b.Navigation("ReportUsers");

                    b.Navigation("SkinToneAnalysisLogs");

                    b.Navigation("TemporaryRoles");

                    b.Navigation("Transactions");

                    b.Navigation("UserPermissions");

                    b.Navigation("UserPromotions");

                    b.Navigation("VipPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
